In [2]:
import pandas as pd

In [7]:
url = "https://raw.githubusercontent.com/yinghaoz1/tmdb-movie-dataset-analysis/master/tmdb-movies.csv"
df = pd.read_csv(url)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   budget                10866 non-null  int64
 4   revenue               10866 non-null  int64
 5   original_title        10866 non-null  object
 6   cast                  10790 non-null  object
 7   homepage              2936 non-null   object
 8   director              10822 non-null  object
 9   tagline               8042 non-null   object
 10  keywords              9373 non-null   object
 11  overview              10862 non-null  object
 12  runtime               10866 non-null  int64
 13  genres                10843 non-null  object
 14  production_companies  9836 non-null   object
 15  release_date          10866 non-null  object
 16  vote_count            10866 non-null  int64
 17  vote_average          10866 non-null  float64
 18  release_year          10866 non-null  int64
 19  budget_adj            10866 non-null  float64
 20  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.7+ MB

In [9]:
#1: Sắp xếp các bộ phim theo ngày phát hành giảm dần rồi lưu ra một file mới
sorted_df = df.sort_values('release_date')
sorted_df.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
8880,48868,tt0400231,0.032577,0,0,The World of Stainboy,NaN,NaN,Tim Burton,NaN,...,Stainboy visits his troubled past.,30,Animation,NaN,1/1/00,10,6.3,2000,0.000000e+00,0.0
8875,20993,tt0238883,0.066233,1500000,0,Ð‘Ñ€Ð°Ñ‚ 2,Sergei Bodrov Jr.|Viktor Sukhorukov|Aleksandr ...,NaN,Aleksey Balabanov,Danila returns!,...,"Arriving in Moscow, Chechen veteran Danila (Se...",122,Drama|Thriller,NaN,1/1/00,18,7.4,2000,1.899438e+06,0.0
8865,20410,tt0253658,0.141201,0,0,Scooby-Doo and the Alien Invaders,Scott Innes|Mary Kay Bergman|Frank Welker|B. J...,NaN,Jim Stenstrum,NaN,...,Scooby and the gang investigate aliens sightin...,74,Animation|Family,NaN,1/1/00,28,6.1,2000,0.000000e+00,0.0
8839,16275,tt0251654,0.157001,0,0,Dave Chappelle: Killin' Them Softly,Dave Chappelle,NaN,Stan Lathan,NaN,...,Dave Chappelle returns for a stand-up to D.C. ...,57,Comedy,NaN,1/1/00,17,8.5,2000,0.000000e+00,0.0
8831,4369,tt0231844,0.171378,0,0,Juste une question d'amour,Cyrille Thouvenin|StÃ©phan GuÃ©rin-TilliÃ©|Car...,NaN,Christian Faure,NaN,...,"After his gay cousin dies from hepatitis, youn...",88,Drama|Romance,NaN,1/1/00,13,7.5,2000,0.000000e+00,0.0

In [10]:
#2: Lọc ra các bộ phim có đánh giá trung bình trên 7.5 rồi lưu ra một file mới
filtered_df = df[df['vote_average'] >= 7.5]
filtered_df.head(10)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/15,4572,7.6,2015,9.935996e+07,5.477497e+08
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/15,3935,8.0,2015,1.609999e+08,7.854116e+08
12,264660,tt0470752,6.118847,15000000,36869414,Ex Machina,Domhnall Gleeson|Alicia Vikander|Oscar Isaac|S...,http://exmachina-movie.com/,Alex Garland,There is nothing more human than the will to s...,...,"Caleb, a 26 year old coder at the world's larg...",108,Drama|Science Fiction,DNA Films|Universal Pictures International (UP...,1/21/15,2854,7.6,2015,1.379999e+07,3.391985e+07
27,207703,tt2802144,4.503789,81000000,403802136,Kingsman: The Secret Service,Taron Egerton|Colin Firth|Samuel L. Jackson|Mi...,http://www.kingsmanmovie.com/,Matthew Vaughn,Manners maketh man.,...,The story of a super-secret spy organization t...,130,Crime|Comedy|Action|Adventure,Twentieth Century Fox Film Corporation|Marv Fi...,1/24/15,3833,7.6,2015,7.451997e+07,3.714978e+08
28,314365,tt1895587,4.062293,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,http://www.spotlightthefilm.com,Tom McCarthy,Break the story. Break the silence.,...,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/15,1559,7.8,2015,1.839999e+07,8.127872e+07
35,264644,tt3170832,3.557846,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,http://www.roomthemovie.com,Lenny Abrahamson,Love knows no boundaries,...,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/15,1520,8.0,2015,5.519998e+06,3.256960e+07
40,277216,tt1398426,3.202719,28000000,201634991,Straight Outta Compton,O'Shea Jackson Jr.|Corey Hawkins|Jason Mitchel...,http://www.straightouttacompton.com/,F. Gary Gray,The Story of N.W.A.,...,"In 1987, five young men, using brutally honest...",147,Drama|Music,New Line Cinema|Universal Pictures|Legendary P...,8/13/15,918,7.7,2015,2.575999e+07,1.855041e+08
75,308369,tt2582496,2.141506,0,0,Me and Earl and the Dying Girl,Thomas Mann|RJ Cyler|Olivia Cooke|Connie Britt...,http://www.foxsearchlight.com/meandearlandthed...,Alfonso Gomez-Rejon,A Little Friendship Never Killed Anyone.,...,Greg is coasting through senior year of high s...,105,Comedy|Drama,Indian Paintbrush,6/12/15,569,7.7,2015,0.000000e+00,0.000000e+00
94,309809,tt1754656,1.865007,64000000,97571250,The Little Prince,Jeff Bridges|Rachel McAdams|Paul Rudd|Marion C...,http://www.thelittleprincemovie.com/,Mark Osborne,Growing up isn't the problem... forgetting is.,...,Based on the best-seller book 'The Little Prin...,92,Adventure|Animation|Fantasy,Onyx Films|Orange Studios|CityMation|On Entert...,7/29/15,423,7.5,2015,5.887997e+07,8.976551e+07

In [13]:
#3: Tìm ra phim nào có doanh thu cao nhất và doanh thu thấp nhất
lowest_revenue = df.sort_values('revenue', ascending=True).head(1)
highest_revenue = df.sort_values('revenue', ascending=False).head(1)
print(lowest_revenue, highest_revenue)

          id    imdb_id  popularity  budget  revenue  \
10865  22293  tt0060666    0.035919   19000        0

                 original_title  \
10865  Manos: The Hands of Fate

                                                    cast homepage  \
10865  Harold P. Warren|Tom Neyman|John Reynolds|Dian...      NaN

               director                                       tagline  ...  \
10865  Harold P. Warren  It's Shocking! It's Beyond Your Imagination!  ...

                                                overview runtime  genres  \
10865  A family gets lost on the road and stumbles up...      74  Horror

      production_companies release_date vote_count  vote_average  \
10865            Norm-Iris     11/15/66         15           1.5

       release_year     budget_adj  revenue_adj
10865          1966  127642.279154          0.0

[1 rows x 21 columns]          id    imdb_id  popularity     budget     revenue original_title  \
1386  19995  tt0499549    9.432768  237000000  2781505847         Avatar

                                                   cast  \
1386  Sam Worthington|Zoe Saldana|Sigourney Weaver|S...

                         homepage       director                      tagline  \
1386  http://www.avatarmovie.com/  James Cameron  Enter the World of Pandora.

      ...                                           overview runtime  \
1386  ...  In the 22nd century, a paraplegic Marine is di...     162

                                        genres  \
1386  Action|Adventure|Fantasy|Science Fiction

                                   production_companies release_date  \
1386  Ingenious Film Partners|Twentieth Century Fox ...     12/10/09

     vote_count  vote_average  release_year    budget_adj   revenue_adj
1386       8458           7.1          2009  2.408869e+08  2.827124e+09

[1 rows x 21 columns]

In [17]:
#4: Tính tổng doanh thu tất cả các bộ phim
total_revenue = df['revenue'].sum()
print(total_revenue)

432720192875

In [18]:
#5: Top 10 bộ phim đem về lợi nhuận cao nhất
top_10_movies = df.sort_values('revenue', ascending=False).head(10)
print(top_10_movies)

          id    imdb_id  popularity     budget     revenue  \
1386   19995  tt0499549    9.432768  237000000  2781505847
3     140607  tt2488496   11.173104  200000000  2068178225
5231     597  tt0120338    4.355219  200000000  1845034188
4361   24428  tt0848228    7.637767  220000000  1519557910
0     135397  tt0369610   32.985763  150000000  1513528810
4     168259  tt2820852    9.335014  190000000  1506249360
14     99861  tt2395427    5.944927  280000000  1405035767
3374   12445  tt1201607    5.711315  125000000  1327817822
5422  109445  tt2294629    6.112766  150000000  1274219009
5425   68721  tt1300854    4.946136  200000000  1215439994

                                    original_title  \
1386                                        Avatar
3                     Star Wars: The Force Awakens
5231                                       Titanic
4361                                  The Avengers
0                                   Jurassic World
4                                        Furious 7
14                         Avengers: Age of Ultron
3374  Harry Potter and the Deathly Hallows: Part 2
5422                                        Frozen
5425                                    Iron Man 3

                                                   cast  \
1386  Sam Worthington|Zoe Saldana|Sigourney Weaver|S...
3     Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...
5231  Kate Winslet|Leonardo DiCaprio|Frances Fisher|...
4361  Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...
0     Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...
4     Vin Diesel|Paul Walker|Jason Statham|Michelle ...
14    Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...
3374  Daniel Radcliffe|Rupert Grint|Emma Watson|Alan...
5422  Kristen Bell|Idina Menzel|Jonathan Groff|Josh ...
5425  Robert Downey Jr.|Gwyneth Paltrow|Guy Pearce|D...

                                               homepage  \
1386                        http://www.avatarmovie.com/
3     http://www.starwars.com/films/star-wars-episod...
5231              http://www.titanicmovie.com/menu.html
4361                  http://marvel.com/avengers_movie/
0                         http://www.jurassicworld.com/
4                              http://www.furious7.com/
14    http://marvel.com/movies/movie/193/avengers_ag...
3374                         http://www.harrypotter.com
5422                    http://movies.disney.com/frozen
5425                         http://marvel.com/ironman3

                     director  \
1386            James Cameron
3                 J.J. Abrams
5231            James Cameron
4361              Joss Whedon
0             Colin Trevorrow
4                   James Wan
14                Joss Whedon
3374              David Yates
5422  Chris Buck|Jennifer Lee
5425              Shane Black

                                                tagline  ...  \
1386                        Enter the World of Pandora.  ...
3                         Every generation has a story.  ...
5231          Nothing on Earth could come between them.  ...
4361                            Some assembly required.  ...
0                                     The park is open.  ...
4                                   Vengeance Hits Home  ...
14                                  A New Age Has Come.  ...
3374                                  It all ends here.  ...
5422  Only the act of true love will thaw a frozen h...  ...
5425                Unleash the power behind the armor.  ...

                                               overview runtime  \
1386  In the 22nd century, a paraplegic Marine is di...     162
3     Thirty years after defeating the Galactic Empi...     136
5231  84 years later, a 101-year-old woman named Ros...     194
4361  When an unexpected enemy emerges and threatens...     143
0     Twenty-two years after the events of Jurassic ...     124
4     Deckard Shaw seeks revenge against Dominic Tor...     137
14    When Tony Stark tries to jumpstart a dormant p...     141
3374  Harry, Ron and Hermione continue their quest t...     130
5422  Young princess Anna of Arendelle dreams about ...     102
5425  When Tony Stark's world is torn apart by a for...     130

                                         genres  \
1386   Action|Adventure|Fantasy|Science Fiction
3      Action|Adventure|Science Fiction|Fantasy
5231                     Drama|Romance|Thriller
4361           Science Fiction|Action|Adventure
0     Action|Adventure|Science Fiction|Thriller
4                         Action|Crime|Thriller
14             Action|Adventure|Science Fiction
3374                   Adventure|Family|Fantasy
5422                 Animation|Adventure|Family
5425           Action|Adventure|Science Fiction

                                   production_companies release_date  \
1386  Ingenious Film Partners|Twentieth Century Fox ...     12/10/09
3             Lucasfilm|Truenorth Productions|Bad Robot     12/15/15
5231  Paramount Pictures|Twentieth Century Fox Film ...     11/18/97
4361                                     Marvel Studios      4/25/12
0     Universal Studios|Amblin Entertainment|Legenda...       6/9/15
4     Universal Pictures|Original Film|Media Rights ...       4/1/15
14    Marvel Studios|Prime Focus|Revolution Sun Studios      4/22/15
3374  Warner Bros.|Heyday Films|Moving Picture Compa...       7/7/11
5422  Walt Disney Pictures|Walt Disney Animation Stu...     11/27/13
5425                                     Marvel Studios      4/18/13

     vote_count  vote_average  release_year    budget_adj   revenue_adj
1386       8458           7.1          2009  2.408869e+08  2.827124e+09
3          5292           7.5          2015  1.839999e+08  1.902723e+09
5231       4654           7.3          1997  2.716921e+08  2.506406e+09
4361       8903           7.3          2012  2.089437e+08  1.443191e+09
0          5562           6.5          2015  1.379999e+08  1.392446e+09
4          2947           7.3          2015  1.747999e+08  1.385749e+09
14         4304           7.4          2015  2.575999e+08  1.292632e+09
3374       3750           7.7          2011  1.211748e+08  1.287184e+09
5422       3369           7.5          2013  1.404050e+08  1.192711e+09
5425       6882           6.9          2013  1.872067e+08  1.137692e+09

[10 rows x 21 columns]

In [31]:
#6: Đạo diễn nào có nhiều bộ phim nhất và diễn viên nào đóng nhiều phim nhất
director_movies = df.groupby('director')['id'].count().sort_values(ascending=False).head(1)
print(director_movies)
actor = df.groupby('cast')['id'].count().sort_values(ascending=False).head(1)
print(actor)

director
Woody Allen    45
Name: id, dtype: int64
cast
Louis C.K.    6
Name: id, dtype: int64

In [52]:
#7: Thống kê số lượng phim theo các thể loại. Ví dụ có bao nhiêu phim thuộc thể loại Action, bao nhiêu thuộc thể loại Family, ….
genres = df['genres'].str.split('|')
genres_exploded = genres.explode('genres').value_counts()
print(genres_exploded)

genres
Drama              4761
Comedy             3793
Thriller           2908
Action             2385
Romance            1712
Horror             1637
Adventure          1471
Crime              1355
Family             1231
Science Fiction    1230
Fantasy             916
Mystery             810
Animation           699
Documentary         520
Music               408
History             334
War                 270
Foreign             188
TV Movie            167
Western             165
Name: count, dtype: int64